# Arreglos

En Python, el manejo de arreglos no se da de forma nativa. Requiere una librería. La más utilizada es `numpy` porque permite la mayoría de las operaciones matemáticas requeridas para trabajar con arreglos.

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 4])

In [3]:
print(arr)

[1 2 4]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# Los objetos tienen atributos y métodos. Dtype es un atributo del tipo de dato array (numpy)
# que permite saber el tipo de dato de los elementos del arreglo
print(arr.dtype  )

int32


In [7]:
arr.astype('float')

array([1., 2., 4.])

In [8]:
arr

array([1, 2, 4])

In [9]:
# Asignar tipo al declarar el arreglo
arr = np.array([1, 3, 4], dtype='float')
print(arr.dtype)

float64


In [10]:
# De forma expresa ingresar valores reales
arr = np.array([1.0, 2.0, 4.0])
print(arr.dtype)

float64


In [13]:
arr.shape

(3,)

In [14]:
arr[0]

1.0

### Crear arreglos vacíos

In [15]:
a = np.zeros(10, dtype='int')
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [16]:
b = np.ones(5, dtype='float')
print(b)

[1. 1. 1. 1. 1.]


In [17]:
c = np.arange(3.0, 9.0, 0.5)  # Funciona igual que el range pero los intervalos pueden ser reales.
print(c)

[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


`linspace(inicio, termino, cantidad de elementos)`

In [18]:

d = np.linspace(1, 5, 4)  # Crea arreglo de valores equiespaciados. (Stop - Start) / n-1
print(d)

[1.         2.33333333 3.66666667 5.        ]


### Operaciones con arreglos

In [22]:
a = np.array([20, 21, 30, 11,  9])
b = np.array([12, -9,  1, 22, -9])

In [23]:
a + b

array([32, 12, 31, 33,  0])

In [24]:
a - b

array([  8,  30,  29, -11,  18])

In [25]:
a * b  # Operación elemento a elemento (Element wise)

array([ 240, -189,   30,  242,  -81])

In [26]:
a / b

array([ 1.66666667, -2.33333333, 30.        ,  0.5       , -1.        ])

In [27]:
# Operación por escalar
0.1 * a

array([2. , 2.1, 3. , 1.1, 0.9])

In [28]:
a + 1

array([21, 22, 31, 12, 10])

In [29]:
a > b

array([ True,  True,  True, False,  True])

In [30]:
all(a == b)

False

In [31]:
np.log(a)

array([2.99573227, 3.04452244, 3.40119738, 2.39789527, 2.19722458])

In [32]:
np.min(a)

9

In [33]:
np.max(a)

30

In [34]:
np.argmin(a)

4

### Obtener valores de un arreglo

In [35]:
a[0]

20

In [36]:
a[1:3]

array([21, 30])

## Arreglos Bidimensionales

In [37]:
a = np.array([[1, 3, 4], [5, 6, 7]], dtype='float')
b = np.array([[5, 7, 9], [1, 3, 2]], dtype='float')

In [38]:
print(a)

[[1. 3. 4.]
 [5. 6. 7.]]


In [39]:
a.shape

(2, 3)

In [40]:
len(a)

2

In [41]:
c = np.zeros((3, 4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
d = np.random.random((3, 3))
print(d)

[[0.16319298 0.76934552 0.95304212]
 [0.59673314 0.99415644 0.97393189]
 [0.51959808 0.1128468  0.10257023]]


In [43]:
d[1, 2]

0.9739318949698406

In [44]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        print(d[i, j])

0.1631929795129865
0.7693455183088729
0.9530421167748481
0.5967331449249069
0.9941564435645616
0.9739318949698406
0.5195980804301786
0.11284680433000238
0.1025702315054684


In [45]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [46]:
b = a.reshape((2, 4))
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [47]:
b.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [48]:
np.transpose(b)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [49]:
# Reducciones
print(b.min(axis=0))

[0 1 2 3]


In [51]:
print(b.sum(axis=1))

[ 6 22]


In [52]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
# Dot
m = np.array([[2, 1], [4, 5]])
n = np.array([[5], [8]])

np.dot(m, n)

array([[18],
       [60]])